### ISSUE TITLE
Error after performing spectro-photometric fitting

### ISSUE THREAD

**Issue by chavezoscar009** [jacopo-chevallard/BEAGLE-public#109]
Hi BEAGLE Team, 

A follow up on Issue #108 

So after I changed the filename to the naming convention required by BEAGLE it seem to have worked as it shows the MultiNest output and the likelihood evaluations. At the end of the evaluations I get this:

ln(ev)=  -654.23889739217873      +/-  0.28518031391471876     
 Total Likelihood Evaluations:        13827
 Sampling finished. Exiting MultiNest
 Param            1  posterior mean:    9.22245407    
 Param            2  posterior mean:   -1.66112494    
 Param            3  posterior mean:  -0.536551893    
 Param            4  posterior mean:    1.59249806    
 Param            5  posterior mean:    7.78284740    
 Param            6  posterior mean:  -0.937654436    
 Param            7  posterior mean:   -7.17411661    
 Param            8  posterior mean:    6.29192162    
 Param            9  posterior mean:    36.2294540    
 BEAGLE here
 Total CPU time:    7709.23633      seconds

Followed by a large error message, of which I'll show the first couple of lines:

profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_padding.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_root_finding.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_rebin.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_kernels.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_integration.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_gnufor.f90.gcda:Skip
profiling:/home:Cannot create directory
profiling:/home/runner/work/BEAGLE/BEAGLE/build/dependencies/astrofortran/CMakeFiles/astrofortran.dir/src/lib_constants.f90.gcda:Skip

Have you all encountered anything like this before? I have attached the param file i used in this issue. Any insights would be greatly appreciated because I modified the spectro_photometric_fit_example.param file. 

[Jorges_Fit.docx](https://github.com/jacopo-chevallard/BEAGLE-general/files/15299348/Jorges_Fit.docx)

**Comment by jacopo-chevallard** [comment]
Hi @chavezoscar009,  those are not error messages, and you can safely ignore them.

The program has actually finished after it prints the total CPU time. You will find the Beagle output files in your results directory, and you can post-process them (make plots, compute summary statistics) using pyp-beagle

**Comment by chavezoscar009** [comment]
Okay cool that is good to know. And yeah I am trying to using pyp_beagle for the output and am running into some errors on that front. I'll submit an issue on the pyp-beagle github
